### ISSUE TITLE
update  gl egl headers

### ISSUE THREAD

**Issue by xlazom00** [linux-sunxi/sunxi-mali#5]
Can we update gles egl header files as mali drivers support some new futures  for example dma-buf as EGLImage

https://codereview.chromium.org/12316111

Also nice future will be to detect if this future is enabled in drivers

**Comment by libv** [comment]
No. Not until we have binaries which we can distribute, and device kernels to match.

**Comment by xlazom00** [comment]
And do you know if it possible to ask drivers if they support specific extension  in EGL. 
I know that in opengl has this future if you want to check supported texture formats for example
